################################################################################
# Azure Pipeline
################################################################################

trigger:
- master

pool:
  vmImage: 'ubuntu-16.04' # examples of other options: 'macOS-10.13', 'vs2017-win2016'

  # Using Variables
  # https://docs.microsoft.com/en-us/azure/devops/pipelines/process/variables?view=azure-devops&tabs=yaml%2Cbatch
variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

stages:

################################################################################
# Restore
################################################################################

- stage: "Restore"
  displayName: "Restore Dependencies"

  jobs:
    - job: "Run dotnet restore"
      steps:
      - script: dotnet restore

################################################################################
# Build
################################################################################

- stage: "Build"
  displayName: "Build Project"

  jobs:
    - job: "Run Build"
      steps:
      # https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/build/dotnet-core-cli?view=azure-devops
      - task: DotNetCoreCLI@2
        displayName: Build
        inputs:
          command: build
          projects: '**/*.csproj'
          arguments: '$(buildConfiguration)'

