################################################################################
# Azure Pipeline
################################################################################

trigger:
- master



  # Using Variables
  # https://docs.microsoft.com/en-us/azure/devops/pipelines/process/variables?view=azure-devops&tabs=yaml%2Cbatch
variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

stages:

################################################################################
# Restore
################################################################################

- stage: "Restore"
  displayName: "Restore Dependencies"

  jobs:
    - job: "Job_dotnet_restore"
      pool:
        vmImage: 'ubuntu-16.04'
      steps:
      - script: dotnet restore NewsAPI.sln

################################################################################
# Build
################################################################################

- stage: "Build"
  displayName: "Build Project"

  jobs:
    - job: "Job_Run_Build"
      pool:
        vmImage: 'ubuntu-16.04'
      steps:
      # https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/build/dotnet-core-cli?view=azure-devops
      - task: DotNetCoreCLI@2
        displayName: Build
        inputs:
          command: build
          projects: 'NewsAPI.sln'
          arguments: '$(buildConfiguration)'

