################################################################################
# Azure Pipeline
################################################################################

trigger:
- master

  # Using Variables
  # https://docs.microsoft.com/en-us/azure/devops/pipelines/process/variables?view=azure-devops&tabs=yaml%2Cbatch
variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'
  vmImage: 'ubuntu-16.04'

stages:

################################################################################
# Restore
################################################################################

- stage: Restore
  displayName: Restore Dependencies

  jobs:
    - job: Job_dotnet_restore
      pool:
        vmImage: '$(vmImage)'
      steps:
      - script: dotnet restore NewsAPI.sln

################################################################################
# Build
################################################################################

- stage: Build
  displayName: "Build Project"

  jobs:
    - job: Job_Run_Build
      pool:
        vmImage: '$(vmImage)'
      steps:
      # https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/build/dotnet-core-cli?view=azure-devops
      - task: DotNetCoreCLI@2
        displayName: Build
        inputs:
          command: build
          projects: '$(solution)'
          arguments: '$(buildConfiguration)'

