################################################################################
# Azure Pipeline
################################################################################

trigger:
- master

  # Using Variables
  # https://docs.microsoft.com/en-us/azure/devops/pipelines/process/variables?view=azure-devops&tabs=yaml%2Cbatch
variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'
  vmImage: 'ubuntu-16.04'

stages:

################################################################################
# Restore
################################################################################

- stage: Restore
  displayName: Restore Dependencies

  jobs:
    - job:
      pool:
        vmImage: '$(vmImage)'
      steps:
      - script: dotnet restore '$(solution)'

################################################################################
# Build
################################################################################

- stage: Build
  displayName: Build Project

  jobs:
    - job: 
      pool:
        vmImage: '$(vmImage)'
      steps:
      - script: dotnet build '$(solution)'